### PR TITLE
1.18

### PR DESCRIPTION
**Pull request by joey-drake**
# Description

Updates Transparent Cosmetics to support 1.18 and removes dependency on the abandoned Artifice library

Resolved issue #2 

I am not much of a Java developer so sorry if there are any mistakes. I will gladly fix if so

### CODE REVIEW

**Comment by gaycookie** [comment]
Hello,

Thanks for your time on the request, I will have a look into it asap.

I'm not that font of separate JSON files for items that is why I kept using Artifice.
But if everything works fine, maybe I have to say bye bye to it then haha.

- GayCookie

**Comment by joey-drake** [comment]
Thanks for checking it out! 
I would've looked for an alternative to avoid the separate JSON files or tried to update Artifice as well, but it seemed, in this case of only five items, to be faster using separate JSON files. If you find an alternative I would be happy to help refactor them back out.

**Comment by gaycookie** [comment]
Hello,

Did you build the mod already locally and tried if it actually works?
Because I seem to get errors from it when I try to use it.

- GayCookie

**Comment by joey-drake** [comment]
I wasn't able to test 1.18.2 due to Cosmetic-Armor not being updated as you said. I did build locally and had 1.18.1 working with no issues both by itself (with dependencies of course) and in a larger modpack.


Here are the versions I used:

- Fabric API 0.46+1.18.1
- Cosmetic Armor 1.2.1
- Trinkets 3.2.0
- My local build of Transparent-Cosmetics

I built by running `$ ./gradlew clean && ./gradlew build`

What errors are you getting? It's very possible I overlooked something as I'm a bit out of my depths when it comes to Minecraft modding lol

Screenshot of me in 1.18.1 with mod working:
image

**Comment by gaycookie** [comment]
Hello,

I think it's just me being dumb, I didn't download the correct version of FabricAPI when I tried different versions.

- GayCookie

**Pull request merged**
